# -*- coding: utf-8 -*-
"""Session_2 DS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yu6enprJzEFzIvkVpkMBfHNf2563YMPs

#### Arrays in python

### Data Structures in python
Data structures stores a set of values.
"""



"""Array consists of set of elements of the same type. Array is mutable that means we can change the elements inside the array or add or remove elements. Each item stored in an array is called an element and each location of an element in an array has a numerical index, which is used to identify the element. Index in array start from 0. In order to create array we use python array module. Arrays are generally defined in []."""

import array
from array import *

#to create an array we use :
#array_name = array('typecode','initialisation') for eg:
arr_ = array('b',[10,20,30,40,50,60])
# the type code specifies the type of the array that we have created, 'b' represents integer type of the array.
arr_

"""#### Operations on Array"""

arr_[3] #to access an element of the array we use array name and square brackets and pass the index number of the element

arr_.insert(2,100) #to insert an element in array we pass the index and the element that we have to insert.
arr_

arr_.index(50) #In order to search for an element inside an array we use index method and pass the element that you want to search

arr_[5]=120 #In order to update any existing element we pass the index the element that has to updated and the new value
arr_

arr_.append(125) # append() inserts the element towards the last of the array
arr_

arr_.count(100) #return the count i.e, number of times the element has appeared

#Concatenation and extending array
#CONCATENATION
#lets create one more array
Arr_ = array('b',[70,80,90])
concat_ = arr_ + Arr_
print (arr_)
print (Arr_)
concat_ #it includes elements of both the arrays and stores it in concat_, but didnt changed the actual arrays arr_ and Arr_

#EXTEND:
#with extend command it changes one of the arrays as,
Arr_.extend(arr_)
print (arr_)
print (Arr_)

#pop: removes the element whose index is passed as a parameter, if no index is passed it removes the last element
arr_.pop()

arr_.remove(10)#removes the element whose value is passed as a parameter
arr_

del(arr_)#to delete the array

"""#### Lists:

Lists consists of set of elements of the multiple type. Lists is mutable that means we can change the elements inside the lists or add or remove elements. Each item stored in list is called an element and each location of an element in list has a numerical index, which is used to identify the element. Index in list start from 0. List are generaly defined in [].
"""

lis_1 = ['abc','xyz','pqr',1,2,3,4,5]
lis_2= [30,12,70,50]
type(lis_1)

"""#### Operation on lists

Lists has the same operations as an array
"""

lis_1.append(10) #append adds the element at the last of the list
lis_1.count(2) #returns the number of appearances of the given element
lis_1.extend(lis_2) #adds elements of the second list in the first list
lis_1.insert(5,50) #inserts the element 50 at index 5
lis_1.pop(2) #pops out the element at index 2
lis_1.remove(3) #remove element = 3
lis_2.sort(reverse = True) #sort the list in an increasing order
print(lis_2)
print (len(lis_2)) #len() function returns the length of the list that is passed

lis_1.clear() #clears all the elements of the list
del(lis_1) #deletes the whole list (no instance in the memory left)

"""#### Tuples

In tuples alse we can store elements of any datatype. Only difference is that we cannot manipulate the tuple or in 
other words tuples are immutable. Tuples are generally defined in ().
"""

tup_1 = (1,2,3,4,'abc','pqr')
tup_2 = (60,70,80)
#we can concatenate two tuples as it wont affect the actual tuples
concat_ = tup_1 + tup_2
print (tup_1)
print (tup_2)
print (concat_)

"""#### Dictionary:

Dictionary store values in key and value format. In order to access values in dictionary we use key's instead of indices.

#### Operation on dictionary:
"""

dict_ = {'john':12345,'michael':67890,'Abrahm':45678,'David':89234,'Smith':23789}
print (dict_['john']) #accessing a value in dictionary we need to call by key

dict_

dict_['Abrahm'] = 12345678 #to change value in dictionary, we directly give new value to that perticular key
dict_

dict_.keys() #to get all keys

dict_.values() #to get all values

dict_['Warner'] = '00000' #to add new value to dictionary we specify the new key and the new value
dict_

dict_.pop('john') #pops out the value of the key that has been passed

dict_.clear() # clears all the element of the dictionary but the instance of the dictionary still remains in the memory
dict_

del(dict_) #deletes the dictionary, i.e no values remain inside the dictionary

"""#### Converting list to tuple and vice-versa"""

x = (1,2,3,4) #tuple
# 'x' is a tuple ,in order to convert tuple to list we use
y = list(x)
y
#Now 'y' is a list, similarly we use tuple() to convert a list to tuple

"""###### Practise Questions:"""

#perform the following operations on the given list.
x = [1,2,3,4,5,6]
# update the element at index 0 by 150
# add an element 50 between 2 and 3
# add an element 100 at the end
# remove element 3 by passing index as parameter
# copy the elements of z = [10,20] in x

# Perform the following operations on the dictionary:
## create a dictionary containing 5 names and their ages
## update the age of one of the person
## insert one more name with age 30
## clear all the elements of this dict